ARG VERSION
FROM almalinux:${VERSION:-9}
ARG COURSE="DOCKER" \
    AUTHOR="VINAY KUMAR" \
    DURATION="1.5 HRS"
RUN echo "Course: ${COURSE}" && \
    echo "Author: ${AUTHOR}" && \
    echo "Duration: ${DURATION}"
CMD ["sleep", "100"]
